[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
todo_sol = "3ibA1xfXF5otPPpL94eoqrSDwVaYrQRz36zAQqtbAzL5"

[programs.localnet]
todo_sol = "3ibA1xfXF5otPPpL94eoqrSDwVaYrQRz36zAQqtbAzL5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
